version: '3.9'

services:

  restapi:
    image: todo_backend
    container_name: todo_backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - todoNet

  postgres:
    image: postgres:15.3-alpine3.18
    container_name: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 60s
    networks:
      - todoNet

networks:
  todoNet:
    driver: bridge
