version: '3.9'

services:

  todobackend:
    image: todobackend
    container_name: todobackend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - todoNet

  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: unless-stopped
    ports:
      - ${POSTGRESS_PORT}:${POSTGRESS_PORT}"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRESS_DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - todoNet

networks:
  todoNet:
    driver: bridge
