http:
  port: 8080
  maxHeaderMegaBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  port: 5432
  username: postgres
  databasename:  postgres

cache:
  ttl: 3600s

auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 30m
  verificationCodeLength: 10
