http:
  port: 8080
  maxHeaderMegaBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  host: localhost
  port: 5432
  username: postgres
  password: qwerty
  databasename:  postgres
  sslmode: none

cache:
  ttl: 3600s

auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 30m
  verificationCodeLength: 10
